[program:xorg]
command=/usr/bin/Xorg :99 -config /etc/X11/xorg.conf -nolisten tcp
autorestart=true
priority=100
stdout_logfile=/var/log/xorg.log
stdout_logfile_maxbytes=100KB
stderr_redirect_with_stdout=true

[program:openbox]
command=/usr/bin/openbox
environment=DISPLAY=":99"
autorestart=true
priority=200
startsecs=2
stdout_logfile=/var/log/openbox.log
stdout_logfile_maxbytes=100KB
stderr_redirect_with_stdout=true

[program:chrome]
command=/usr/local/bin/chrome
  --no-first-run
  --no-sandbox
  --disable-gpu
  --disable-software-rasterizer
  --disable-dev-shm-usage
  --disable-blink-features=AutomationControlled
  --remote-debugging-port=9222
  --user-data-dir=/data/profile
  --display=:99
  --window-position=0,0
  --start-maximized
environment=HOME="/home/neko",DISPLAY=":99"
user=neko
autorestart=true
priority=300
startsecs=3
startretries=3
stdout_logfile=/var/log/chrome.log
stdout_logfile_maxbytes=100KB
stderr_redirect_with_stdout=true

[program:socat]
command=/usr/bin/socat TCP-LISTEN:9223,fork,reuseaddr,bind=0.0.0.0 TCP:127.0.0.1:9222
autorestart=true
priority=400
startsecs=1
stdout_logfile=/var/log/socat.log
stdout_logfile_maxbytes=100KB
stderr_redirect_with_stdout=true
