[program:chromium]
environment=HOME="/home/neko",DISPLAY="%(ENV_DISPLAY)s"
command=/usr/bin/chromium
  --window-position=0,0
  --display=%(ENV_DISPLAY)s
  --user-data-dir=/data/profile
  --no-first-run
  --start-maximized
  --no-sandbox
  --force-dark-mode
  --disable-file-system
  --disable-gpu
  --disable-software-rasterizer
  --disable-dev-shm-usage
autorestart=true
priority=800
user=neko
stdout_logfile=/var/log/neko/chromium.log
stdout_logfile_maxbytes=100KB
stdout_logfile_backups=0
stderr_redirect_with_stdout=true
startretries=3
startsecs=3
