[program:chromium]
environment=HOME="/home/%(ENV_USER)s",USER="%(ENV_USER)s",DISPLAY="%(ENV_DISPLAY)s"
command=/usr/bin/chromium
  --remote-debugging-port=9222
  --disable-blink-features=AutomationControlled
  --window-position=0,0
  --display=%(ENV_DISPLAY)s
  --user-data-dir=/data/profile
  --no-first-run
  --start-maximized
  --disable-gpu
  --disable-dev-shm-usage
stopsignal=INT
autorestart=true
priority=800
user=%(ENV_USER)s
