[program:xorg]
command=/usr/bin/Xorg :99 -config /etc/X11/xorg.conf -noreset +extension GLX +extension RANDR +extension RENDER
autorestart=true
priority=100
stdout_logfile=/var/log/xorg.log
redirect_stderr=true

[program:openbox]
command=/usr/bin/openbox
environment=DISPLAY=":99"
autorestart=true
priority=200
stdout_logfile=/var/log/openbox.log
redirect_stderr=true

[program:chrome]
command=/opt/chrome/chrome
  --remote-debugging-port=9222
  --no-first-run
  --no-sandbox
  --disable-blink-features=AutomationControlled
  --user-data-dir=/data/profile
  --display=:99
  --window-position=0,0
  --start-maximized
  --disable-gpu
  --disable-software-rasterizer
  --disable-dev-shm-usage
environment=DISPLAY=":99",HOME="/root"
autorestart=true
priority=300
stdout_logfile=/var/log/chrome.log
redirect_stderr=true

[program:socat]
command=/usr/bin/socat TCP-LISTEN:9223,fork,reuseaddr,bind=0.0.0.0 TCP:127.0.0.1:9222
autorestart=true
priority=400
stdout_logfile=/var/log/socat.log
redirect_stderr=true
