[program:chromium]
environment=DISPLAY=":99",HOME="/root"
command=/usr/bin/chromium
  --remote-debugging-port=9222
  --remote-debugging-address=0.0.0.0
  --disable-blink-features=AutomationControlled
  --window-position=0,0
  --display=:99
  --user-data-dir=/data/profile
  --no-first-run
  --start-maximized
  --disable-gpu
  --disable-dev-shm-usage
  --disable-software-rasterizer
autorestart=true
priority=300
user=root
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0
stderr_logfile=/dev/stderr
stderr_logfile_maxbytes=0
