[program:chromium]
environment=HOME="/home/%(ENV_USER)s",USER="%(ENV_USER)s",DISPLAY=":99.0"
command=/usr/bin/chromium
  --remote-debugging-port=9222
  --remote-debugging-address=0.0.0.0
  --disable-blink-features=AutomationControlled
  --user-data-dir=/data/profile
  --no-first-run
  --start-maximized
  --disable-gpu
  --disable-dev-shm-usage
stopsignal=INT
autorestart=true
priority=800
user=%(ENV_USER)s
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0
stderr_logfile=/dev/stderr
stderr_logfile_maxbytes=0
