[program:openbox]
environment=DISPLAY=":99.0",HOME="/home/%(ENV_USER)s"
command=/usr/bin/openbox --sm-disable
autorestart=true
priority=200
user=%(ENV_USER)s
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0
stderr_logfile=/dev/stderr
stderr_logfile_maxbytes=0
