[program:openbox]
environment=DISPLAY=":99",HOME="/root"
command=/usr/bin/openbox --sm-disable
autorestart=true
priority=200
user=root
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0
stderr_logfile=/dev/stderr
stderr_logfile_maxbytes=0
