[program:xorg]
command=/usr/bin/Xorg :99.0 -config /etc/neko/xorg.conf -nolisten tcp -ac +iglx
autorestart=true
priority=100
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0
stderr_logfile=/dev/stderr
stderr_logfile_maxbytes=0
